server:
  port: 8989
#  servlet:
#    context-path: /api
app:
  name: "marella-store-0.0.1-SNAPSHOT service"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anthony?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=UTC
    username: rudy2128
    password:  Lr-(k[u(vRGxhHjZ
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    mvc.pathmatch.matching-strategy: ant_path_matcher


  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect


